# Generated by Django 5.0 on 2023-12-17 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='product_images/', verbose_name='Image'),
        ),
    ]
